//CONSTANTS TO GET MOVIES LIST
export const GET_MOVIES_LIST_REQUEST = "GET_MOVIES_LIST_REQUEST";
export const GET_MOVIES_LIST_SUCCESS = "GET_MOVIES_LIST_SUCCESS";
export const GET_MOVIES_LIST_ERROR = "GET_MOVIES_LIST_ERROR";

//CONSTANTS TO GET A MOVIES DETAILS 
export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_ERROR = "GET_MOVIE_DETAILS_ERROR";

//CONSTANTS TO SEATCH  MOVIES  ONLINE
export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_ERROR = 'SEARCH_MOVIES_ERROR';

//CONSTANTS TO CLEAR SEARCH QUERY
export const CLEAR_SEARCH_MOVIES_REQUEST = 'CLEAR_SEARCH_MOVIES_REQUEST';
export const CLEAR_SEARCH_MOVIES_SUCCESS = 'CLEAR_SEARCH_MOVIES_SUCCESS';
